apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: app1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1-sa
  namespace: app1
  annotations:
    vault.hashicorp.com/alias-metadata-project: app1
    vault.hashicorp.com/alias-metadata-stage: dev
    vault.hashicorp.com/alias-metadata-component: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1-deployment
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
    spec:
      serviceAccountName: app1-sa
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - mountPath: /var/run/secrets/tokens
            name: vault-token
      volumes:
      - name: vault-token
        projected:
          sources:
          - serviceAccountToken:
              path: vault-token
              expirationSeconds: 7200
              audience: vault
