apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: vso-example-ns
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: vault-secrets-operator
  name: default
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: vso-example-ns
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-example-app
    serviceAccount: vso-example-sa
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: test-static-secret
  namespace: vso-example-ns
spec:
  type: kv-v2
  # mount path
  mount: vso-example-app
  # path of the secret
  path: app-login
  # dest k8s secret
  destination:
    name: test-secret
    create: true
  # static secret refresh interval
  refreshAfter: 10s
  # restart vso-example-app on changes
  rolloutRestartTargets:
    - kind: Deployment
      name: vso-example-app-deployment
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-example-sa
  namespace: vso-example-ns
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: vso-example-app
  namespace: vso-example-ns
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: vso-example-app-deployment
  namespace: vso-example-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      serviceAccountName: vso-example-sa
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-nginx
        image: nginx
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password
        command: ["/bin/bash"]
        args: ["-c", 'printf "username: $USERNAME<br>\npassword: $PASSWORD\n" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
