# XFrontend XRD (Same structure for XBackend and XAPI)
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xfrontends.example.com
spec:
  scope: Namespaced
  group: example.com
  names:
    kind: XFrontend
    plural: xfrontends
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              prefix: { type: string }
          status:
            type: object
            properties:
              message:
                type: string